version: '3.7'
services: 
    backend: 
        image: todo-native-backend
        build: ./backend
        ports: 
            - "5000:5000"
        volumes: 
            - ./backend:/backend
            - /backend/node_modules
        depends_on:
            - postgres
        links: 
            - postgres
        networks: 
            - todo-native-network
    
    expo:
        image: todo-native-frontend
        build: ./frontend
        entrypoint: ["expo","start"]
        ports: 
            - "19000:19000"
            - "19001:19001"
            - "19002:19002"
        volumes: 
            - ./frontend:/frontend
            - /frontend/node_modules
        environment:
            - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.107
            - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 
        links: 
            - backend
        networks: 
            - todo-native-network
        stdin_open: true
        restart: always
    
    postgres: 
        image: postgres
        environment: 
                POSTGRES_PASSWORD: postgresadmin
                POSTGRES_USER: postgres
                POSTGRES_DB: todomobile
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports: 
            - "5432:5432"
        restart: always    
        networks: 
            -  todo-native-network

networks: 
    todo-native-network:
        driver: bridge
